name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    permissions: write-all
    environment: 
      name: Production
    strategy:
      matrix:
        ruby:
          - '3.3.0'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
      env:
        SERVICE_NOW_INSTANCE: ${{ secrets.SERVICE_NOW_INSTANCE }}
        SERVICE_NOW_USERNAME: ${{ secrets.SERVICE_NOW_USERNAME }}
        SERVICE_NOW_PASSWORD: ${{ secrets.SERVICE_NOW_PASSWORD }}
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
